version: 1
sources:
  - type: filesystem
    path: .
    exclude:
      - "**/node_modules/**"
      - "**/vendor/**"
      - "**/dist/**"
      - "**/build/**"
      - "**/.git/**"
      - "**/.github/**"
      - "**/.idea/**"
      - "**/__pycache__/**"
      - "**/*.min.js"
      - "**/*.min.css"

detectors:
  # 비활성화할 검출기 목록 (필요시 주석 해제)
  # disable:
  #   - aws
  #   - github
  #   - slack

# 결과 출력 옵션
output:
  # JSON 형식으로 출력 (기본값: false)
  json: false
  # 상세 로그 출력 (기본값: false)
  verbose: false
  # 색상 출력 (기본값: true)
  color: true
