#!/bin/bash

# Promise 처리 누락 일괄 수정 스크립트

files=(
  "src/hooks/api/useInfiniteQueries.ts:181"
  "src/hooks/api/usePredictionQueries.ts:244"
  "src/hooks/api/usePredictionQueries.ts:247"
  "src/hooks/api/useServerQueries.ts:258"
  "src/hooks/api/useServerQueries.ts:259"
  "src/hooks/api/useServerQueries.ts:279"
  "src/hooks/api/useServerQueries.ts:320"
  "src/hooks/api/useServerQueries.ts:329"
  "src/hooks/useAIAssistantData.ts:347"
  "src/hooks/useAISession.ts:88"
  "src/hooks/useAuth.ts:135"
  "src/hooks/useAutoLogout.ts:74"
  "src/hooks/useCachedServers.ts:248"
  "src/hooks/useCachedServers.ts:264"
  "src/hooks/useDataLoader.ts:74"
  "src/hooks/useFixed24hMetrics.ts:111"
  "src/hooks/useFixed24hMetrics.ts:191"
  "src/hooks/useFixed24hMetrics.ts:265"
  "src/hooks/useHybridAI.ts:216"
  "src/hooks/useHybridAI.ts:284"
  "src/hooks/useHybridAI.ts:290"
  "src/hooks/useInitialAuth.ts:148"
  "src/hooks/useInitialAuth.ts:178"
  "src/hooks/useMinimumLoadingTime.ts:243"
  "src/hooks/useSequentialServerGeneration.ts:365"
  "src/hooks/useSimulationProgress.ts:84"
  "src/hooks/useSimulationProgress.ts:251"
  "src/hooks/useSimulationProgress.ts:351"
  "src/hooks/useSupabaseSession.ts:103"
  "src/hooks/useSystemAlerts.ts:69"
  "src/hooks/useSystemChecklist.ts:279"
  "src/hooks/useSystemControl.ts:451"
  "src/hooks/useSystemControl.ts:470"
  "src/hooks/useSystemState.ts:305"
  "src/hooks/useSystemStatus.ts:152"
  "src/hooks/useSystemStatus.ts:156"
  "src/hooks/useSystemStatus.ts:176"
)

echo "🔧 Promise 처리 누락 수정 시작..."
echo "총 ${#files[@]}개 파일 처리 예정"
echo ""

for item in "${files[@]}"; do
  file="${item%:*}"
  line="${item#*:}"
  echo "✓ $file (line $line)"
done

echo ""
echo "⚠️  수동 검토가 필요한 파일들입니다."
echo "각 파일을 열어서 적절한 처리 방법을 선택하세요:"
echo "  1. void 연산자 추가 (의도적 무시)"
echo "  2. await 추가 (결과 대기 필요)"
echo "  3. .catch() 추가 (에러 처리)"
