# Render Configuration
services:
  - type: web
    name: openmanager-vibe-v5
    runtime: node
    plan: starter
    region: oregon
    branch: main
    rootDir: .
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: 'true'
      - key: NODE_OPTIONS
        value: '--max-old-space-size=1024'
      - key: NEXT_TELEMETRY_DISABLED
        value: '1'
      - key: GITHUB_TOKEN
        sync: false # 수동으로 Render 대시보드에서 설정
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
    disk:
      name: openmanager-data
      mountPath: /opt/render/project/data
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 2
      targetMemoryPercent: 75
      targetCPUPercent: 75
