# ============================================================================
# OpenManager VIBE - Cloud Build Configuration
# Builds and deploys LangGraph AI Backend to Cloud Run
# ============================================================================

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/openmanager/ai-backend:${SHORT_SHA}'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/openmanager/ai-backend:latest'
      - '.'
    dir: 'cloud-run/ai-backend'

  # Step 2: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/openmanager/ai-backend:${SHORT_SHA}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/openmanager/ai-backend:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ai-backend'
      - '--image'
      - 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/openmanager/ai-backend:${SHORT_SHA}'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '3'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300s'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - 'GROQ_API_KEY=groq-api-key:latest,GOOGLE_AI_API_KEY=google-ai-api-key:latest,SUPABASE_URL=supabase-url:latest,SUPABASE_SERVICE_ROLE_KEY=supabase-service-role-key:latest'

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Substitutions (can be overridden)
substitutions:
  _REGION: 'asia-northeast3'

# Images to be stored
images:
  - 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/openmanager/ai-backend:${SHORT_SHA}'
  - 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/openmanager/ai-backend:latest'

# Timeout
timeout: '1200s'
