# Render Configuration
services:
  - type: web
    name: openmanager-mcp-server
    runtime: node
    plan: free
    region: oregon
    branch: main
    rootDir: mcp-server
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: 'true'
      - key: AI_ENGINE_MODE
        value: 'true'
      - key: NODE_OPTIONS
        value: '--max-old-space-size=512'
      - key: NEXT_TELEMETRY_DISABLED
        value: '1'
      - key: PROJECT_ROOT
        value: /opt/render/project/src
      - key: GITHUB_TOKEN
        sync: false # 수동으로 Render 대시보드에서 설정
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
    # 무료 플랜에서는 persistent disk와 scaling 미지원
    # disk:
    #   name: openmanager-data
    #   mountPath: /opt/render/project/data
    #   sizeGB: 1
    # scaling:
    #   minInstances: 1
    #   maxInstances: 2
    #   targetMemoryPercent: 75
    #   targetCPUPercent: 75
