services:
  - type: web
    name: openmanager-ai-python
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    env:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 10000
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: info
      - key: OPENAI_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
    healthCheckPath: /
    numInstances: 1
    autoDeploy: true
    region: oregon
    disk:
      size: 1GB
      mount: /tmp
    scaling:
      minInstances: 0
      maxInstances: 1
      cooldownPeriod: 5m
      targetCPUPercent: 80
      targetMemoryPercent: 80
