#!/bin/bash

# Qwen CLI Wrapper - YOLO Mode
# 버전: 2.6.0
# 날짜: 2025-10-24 (Decision Log auto-logging 추가 - Phase 1)
# 변경: AI 실행 결과를 자동으로 Decision Log에 기록

set -euo pipefail

# 프로젝트 루트 자동 결정 (포터블)
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# Decision Log directories (Phase 1 Auto-logging)
DECISION_LOG_DIR="${PROJECT_ROOT}/logs/ai-decisions"
DECISION_LOG_FILE="$DECISION_LOG_DIR/auto-log-$(date +%Y-%m-%d).md"

# 색상 정의
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# 로그 디렉터리
# 로그 디렉터리 (프로젝트 루트 기준)
LOG_DIR="${PROJECT_ROOT}/logs/ai-perf"
LOG_FILE="$LOG_DIR/qwen-perf-$(date +%F).log"
mkdir -p "$LOG_DIR"

# 로그 함수
log_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] INFO: $1" >> "$LOG_FILE"
}

log_success() {
    echo -e "${GREEN}✅ $1${NC}"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] SUCCESS: $1" >> "$LOG_FILE"
}

log_error() {
    echo -e "${RED}❌ $1${NC}"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $1" >> "$LOG_FILE"
}

log_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] WARNING: $1" >> "$LOG_FILE"
}

# Decision Log auto-logging (Phase 1)
append_to_decision_log() {
    local ai_name="$1"
    local query="$2"
    local duration="$3"
    local tokens="${4:-N/A}"
    local output="$5"

    # Create directory (ignore failures)
    mkdir -p "$DECISION_LOG_DIR" 2>/dev/null || true

    # File header (first run only)
    if [ ! -f "$DECISION_LOG_FILE" ]; then
        {
            echo "# AI Decision Log - $(date +%Y-%m-%d)"
            echo ""
            echo "**Auto-generated by AI wrapper scripts (Phase 1)**"
            echo ""
            echo "---"
        } > "$DECISION_LOG_FILE" 2>/dev/null || return 0
    fi

    # Query summary (first 100 chars)
    local query_summary=$(echo "$query" | head -c 100 | tr '\n' ' ')
    [ ${#query} -gt 100 ] && query_summary="${query_summary}..."

    # Append to Decision Log (ignore failures)
    {
        echo ""
        echo "### $(date +%H:%M:%S) - $ai_name"
        echo "**Query**: $query_summary"
        echo "**Duration**: ${duration}s | **Tokens**: $tokens"
        echo ""
        echo "<details>"
        echo "<summary>전체 결과 보기</summary>"
        echo ""
        echo '```'
        echo "$output"
        echo '```'
        echo ""
        echo "</details>"
        echo ""
        echo "---"
    } >> "$DECISION_LOG_FILE" 2>/dev/null || {
        log_warning "Decision Log 업데이트 실패 (무시)"
        return 0
    }

    log_info "📝 Decision Log 업데이트: $DECISION_LOG_FILE"
}

# 고정 타임아웃 (10분)
TIMEOUT_SECONDS=600

# Qwen 실행 함수
execute_qwen() {
    local query="$1"
    
    log_info "⚙️  Qwen YOLO Mode 실행 중 (타임아웃 ${TIMEOUT_SECONDS}초 = 10분)..."

    local start_time=$(date +%s)
    local output_file=$(mktemp)
    local exit_code=0

    # YOLO Mode: 모든 도구 자동 승인, 완전 무인 동작
    if timeout "${TIMEOUT_SECONDS}s" qwen --approval-mode yolo -p "$query" > "$output_file" 2>&1; then
        exit_code=0
    else
        exit_code=$?
    fi

    local end_time=$(date +%s)
    local duration=$((end_time - start_time))

    if [ $exit_code -eq 0 ]; then
        log_success "Qwen 실행 성공 (${duration}초)"
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] MODE: YOLO, DURATION: ${duration}s" >> "$LOG_FILE"

        # Auto-logging to Decision Log (Phase 1)
        append_to_decision_log "Qwen" "$query" "$duration" "N/A" "$(cat "$output_file")" || true

        cat "$output_file"
        rm -f "$output_file"
        return 0
    elif [ $exit_code -eq 124 ]; then
        log_error "Qwen 타임아웃 (${TIMEOUT_SECONDS}초 = 10분 초과)"
        echo ""
        echo -e "${YELLOW}💡 타임아웃 해결 방법:${NC}"
        echo "  1️⃣  질문을 더 작은 단위로 분할하세요"
        echo "  2️⃣  질문을 더 간결하게 만드세요"
        echo "  3️⃣  핵심 부분만 먼저 질문하세요"
        echo ""
        rm -f "$output_file"
        return 124
    else
        log_error "Qwen 실행 오류 (종료 코드: $exit_code)"
        cat "$output_file" >&2
        rm -f "$output_file"
        return $exit_code
    fi
}

# 도움말
usage() {
    cat << EOF
${CYAN}🟡 Qwen CLI Wrapper v2.6.0 - Claude Code 내부 도구${NC}

${YELLOW}⚠️  이 스크립트는 Claude Code가 제어하는 내부 도구입니다${NC}
${YELLOW}   사용자는 직접 실행하지 않고, 서브에이전트를 통해 사용합니다${NC}

${RED}🚨 YOLO Mode 보안 경고:${NC}
${RED}   - 모든 도구 호출을 자동 승인 (--approval-mode yolo)${NC}
${RED}   - 읽기 전용 분석 작업에만 안전${NC}
${RED}   - 파일 수정/삭제 작업 시 주의 필요${NC}
${RED}   - 신뢰할 수 없는 입력에 사용 금지${NC}

사용 방법:
  ${GREEN}사용자${NC}: "성능 최적화를 AI 교차검증해줘"
  ${GREEN}Claude${NC}: Task multi-ai-verification-specialist 호출
  ${GREEN}서브에이전트${NC}: 이 wrapper를 자동 실행

직접 실행 (디버깅/테스트 전용):
  $0 "쿼리 내용"              # Plan Mode (기본값, 승인 불필요)

옵션:
  -h    도움말 표시

예시 (디버깅):
  $0 "성능 병목점 분석"
  $0 "복잡한 리팩토링 계획"
  $0 "알고리즘 최적화 방안"

특징 (v2.6.0):
  🚀 YOLO Mode (--approval-mode yolo) - 완전 무인 동작
  🚨 보안 경고 강화 (읽기 전용 분석에만 안전)
  ✅ 환경변수 로딩 표준화 (.env.local)
  ✅ 고정 타임아웃: 600초 (10분)
  ✅ 재시도 없음 (자원 낭비 방지)
  ✅ 타임아웃 시 분할/간소화 제안
  ✅ 성능 로깅 ($LOG_FILE)

v2.6.0 개선 사항 (Phase 1):
  📝 Decision Log 자동 기록: logs/ai-decisions/auto-log-YYYY-MM-DD.md
  ⏱️  메타데이터 자동 추출: 시간, 토큰, 쿼리, 결과
  ✅ 80% 시간 절약: 30분 → 6분 (수동 문서 작성 불필요)

v2.5.0 개선 사항:
  🚨 보안 경고 추가: YOLO Mode 위험성 명시
  ✅ 환경변수 로딩: 다른 wrapper와 동일 패턴
  📋 버전 라벨 통일: v2.5.0 (Codex/Gemini와 동기화)

v2.3.0 이전 성과:
  🚀 YOLO Mode 채택: 완전 무인 동작 (Plan Mode 블로킹 해결)
  ⏱️  타임아웃 600초: 복잡한 분석 대응 (TypeScript 타입 시스템 등)
  ✅ 간단한 쿼리: 24초 → 16초 (33% 개선)
  ✅ 복잡한 React 쿼리: 111초 → 108초
  ✅ 복잡한 TypeScript 쿼리: 300초+ 타임아웃 → 121초 성공

타임아웃 발생 시:
  - 질문을 더 작은 단위로 분할
  - 질문을 더 간결하게 수정
  - 핵심 부분만 먼저 질문

로그 위치:
  $LOG_FILE
EOF
    exit 1
}

# 메인 실행
main() {
    local query=""

    # 파라미터 파싱
    while getopts "hp" opt; do
        case $opt in
            h)
                usage
                ;;
            p)
                # -p 옵션은 무시 (v2.3.0에서는 항상 plan mode)
                # 하위 호환성을 위해 허용만 함
                ;;
            \?)
                echo "잘못된 옵션: -${OPTARG:-unknown}" >&2
                usage
                ;;
        esac
    done
    shift $((OPTIND-1))

    # 쿼리 확인
    if [ $# -eq 0 ]; then
        echo "오류: 쿼리를 입력해주세요" >&2
        usage
    fi

    query="$1"

    # Qwen CLI 설치 확인
    if ! command -v qwen >/dev/null 2>&1; then
        log_error "Qwen CLI가 설치되지 않았습니다"
        log_info "설치: npm install -g qwen-cli"
        exit 1
    fi

    # 환경변수 확인 (선택적)
    # 환경변수 확인 (선택적, 프로젝트 루트 기준)
    if [ -f "${PROJECT_ROOT}/.env.local" ]; then
        # shellcheck disable=SC1091
        source "${PROJECT_ROOT}/.env.local" 2>/dev/null || true
    fi

    echo ""
    log_info "🚀 Qwen Wrapper v2.6.0 시작"
    echo ""

    if execute_qwen "$query"; then
        echo ""
        log_success "✅ 완료"
        exit 0
    else
        echo ""
        log_error "❌ 실패"
        exit 1
    fi
}

main "$@"
